name: hotel_booking_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_timer_countdown: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  fluttertoast: ^8.2.5
  light_bottom_navigation_bar: ^0.0.3
  table_calendar: ^3.1.2
  google_maps_flutter: ^2.9.0
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_launcher_icons:
      android: true
      image_path: "assets/app_icon/app_icon.png"
      min_sdk_android: 21


flutter:


  uses-material-design: true


  assets:
      - assets/image/
      - assets/app_icon/

